"""initial_schema

Revision ID: 234dbe10ebe5
Revises: 
Create Date: 2026-03-26 09:22:47.253035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — required for sqlmodel.sql.sqltypes.AutoString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234dbe10ebe5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('preferred_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notify_welcome', sa.Boolean(), nullable=False),
    sa.Column('notify_low_credits', sa.Boolean(), nullable=False),
    sa.Column('notify_ingestion_complete', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referred_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('referral_reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('low_credits_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('notify_account_deletion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('source_authority_weights',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'source_type')
    )
    op.create_table('system_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_profiles_user_id'), 'system_profiles', ['user_id'], unique=False)
    op.create_table('meta_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contributing_memory_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['system_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_documents_user_id'), 'meta_documents', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['system_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sources_user_ingested', 'sources', ['user_id', 'ingested_at'], unique=False)
    op.create_index(op.f('ix_sources_sha256_hash'), 'sources', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_index(op.f('ix_sources_user_id'), 'sources', ['user_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('incumbent_memory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenger_memory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incumbent_source_id', sa.Uuid(), nullable=True),
    sa.Column('challenger_source_id', sa.Uuid(), nullable=True),
    sa.Column('incumbent_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenger_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_proposed_resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenger_source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['incumbent_source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['system_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conflicts_user_status_created', 'conflicts', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_conflicts_status'), 'conflicts', ['status'], unique=False)
    op.create_index(op.f('ix_conflicts_user_id'), 'conflicts', ['user_id'], unique=False)
    op.create_table('job_statuses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_statuses_user_id'), 'job_statuses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_statuses_user_id'), table_name='job_statuses')
    op.drop_table('job_statuses')
    op.drop_index(op.f('ix_conflicts_user_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_status'), table_name='conflicts')
    op.drop_index('idx_conflicts_user_status_created', table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_sources_user_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_sha256_hash'), table_name='sources')
    op.drop_index('idx_sources_user_ingested', table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_meta_documents_user_id'), table_name='meta_documents')
    op.drop_table('meta_documents')
    op.drop_index(op.f('ix_system_profiles_user_id'), table_name='system_profiles')
    op.drop_table('system_profiles')
    op.drop_table('source_authority_weights')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
